
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjnmlnysorjswwbjazkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqbm1sbnlzb3Jqc3d3Ymphemt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MDU0NjgsImV4cCI6MjA2MjA4MTQ2OH0.zOqMLN2460i-19NpUMy8BV05v0p97cBjZBhjcGgM1IQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
